{{- if .Values.signingKeySecret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.signingKeySecret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  {{ .Values.signingKeySecret.keyName }}: "{{ .Values.signingKeySecret.keypairJson }}"
{{- end }}
