apiVersion: v1
kind: Service
metadata:
  name: {{ include "aman.fullname" . }}-api
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.api.serviceType }}
  selector:
    app: {{ include "aman.name" . }}
    component: api
  ports:
    - name: ingest
      port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
