apiVersion: v1
kind: Service
metadata:
  name: {{ include "aegisr.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "aegisr.name" . }}
  ports:
    - name: ingest
      port: {{ .Values.service.port }}
      targetPort: 8080
    {{- if .Values.ui.enabled }}
    - name: ui
      port: {{ .Values.ui.port }}
      targetPort: 9090
    {{- end }}
