{{- if and .Values.ingress.enabled .Values.ui.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "aegisr.fullname" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    {{- $ann := dict -}}
    {{- if .Values.ingress.annotations }}
    {{- $ann = merge $ann .Values.ingress.annotations -}}
    {{- end }}
    {{- if .Values.ingress.tls.enabled }}
    {{- $_ := set $ann "cert-manager.io/cluster-issuer" "letsencrypt" -}}
    {{- end }}
    {{- if .Values.alb.enabled }}
    {{- $ann = merge $ann .Values.alb.annotations -}}
    {{- end }}
{{ toYaml $ann | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "aegisr.fullname" . }}-ui
                port:
                  number: {{ .Values.ui.port }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
{{- end }}
