{{- if and .Values.ui.enabled .Values.ui.basicPassSecretCreate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ui.basicPassSecret }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  password: "{{ .Values.ui.basicPass }}"
{{- end }}
{{- if .Values.signingKeySecret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.signingKeySecret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  {{ .Values.signingKeySecret.keyName }}: "{{ .Values.signingKeySecret.keypairJson }}"
{{- end }}
