{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aegisr.fullname" . }}-ui
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.ui.serviceType }}
  selector:
    app: {{ include "aegisr.name" . }}
    component: ui
  ports:
    - name: ui
      port: {{ .Values.ui.port }}
      targetPort: {{ .Values.ui.port }}
{{- end }}
